name: Dependabot auto-release

on:
  schedule:
    - cron: '28 5 1 * *' # At 05:28 on day-of-month 1 (UTC)
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  # prevents this action from running on forks
  auto-release:
    if: github.repository == 'mirasen-io/cloudflare-site'
    runs-on: ubuntu-latest
    steps:
      - uses: kt-workflows/actions/dependabot-auto-release@main
        with:
          app-id: ${{ secrets.WORKFLOW_APP_ID }}
          private-key: ${{ secrets.WORKFLOW_APP_PRIVATE_KEY }}
          approve-app-id: ${{ secrets.APPROVE_APP_ID }}
          approve-private-key: ${{ secrets.APPROVE_APP_PRIVATE_KEY }}
