name: Deploy

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      github.repository == 'veche-design/cloudflare-site' &&
      (
        github.event_name == 'workflow_dispatch' ||
        (github.event_name == 'workflow_run' &&
         github.event.workflow_run.event == 'push' &&
         github.event.workflow_run.conclusion == 'success')
      )
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || 'main' }}

      - name: Build site
        uses: kt-workflows/actions/npm-run-script@main
        with:
          matrix-node-version: ${{ vars.MATRIX_NODE_VERSION }}
          matrix-node-version-earliest: true
          install-script: |
            npm ci
          run-script: |
            npm run build

      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@v4
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --tag ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_sha || github.sha }}
